name: $(Build.BuildId)

trigger: 
 branches:
   include:
     - master

variables:
- group: Secrets
- name: 'AppVersion'
  value: '1.0.[yyyyWW].*'

pool:
  name: WaldoHetzner

steps:
- checkout: self
  clean: true 

# This compiler (v2) is not going to use a docker container, but it's going to use the artifacts that you specify in the parameters
# The compiler will "Batch Compile", meaning: it will compile everything in the workingfolder

- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: 'Sandbox'
    appversiontemplate: '1.0.*.0'
    versionselect: NextMajor
    sastoken: $(bc.sasToken)