name: $(Build.BuildId)

variables:
- group: Secrets
- name: 'AppVersion'
  value: '1.0.[yyyyWW].*'

pool:
  name: WaldoHetzner

steps:
- checkout: self
  clean: true

- task: ALOpsDockerCreate@1
  inputs:
    artifacttype: OnPrem

- task: ALOpsDockerStart@1
  inputs:

- task: ALOpsDockerWait@1
  inputs:
    search_string: 'Ready for connections!'

- task: ALOpsLicenseImport@1
  inputs:
    usedocker: true
    license_path: $(bc.license)
    
- task: ALOpsAppCompiler@1
  inputs:
    usedocker: true
    nav_app_version: $(AppVersion)
    failed_on_warnings: false    

- task: ALOpsAppPublish@1
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'   
    skip_verification: true 

- task: ALOpsAppTest@1
  inputs:
    usedocker: true
    import_action: "Skip"
    testfilter: $(TestFilter)
    show_available_tests: true
  continueOnError: true    

- task: PublishTestResults@2
  inputs:
    testResultsFormat: XUnit
    testResultsFiles: '**/TestResults.xml'
    testRunTitle: 'BC Test Results: $(Build.BuildId)'

- task: ALOpsDockerRemove@1
  enabled: true
  condition: always()    
